// playground/src/slices/Quote/index.tsx
import { Content, isFilled } from "@prismicio/client";
import { PrismicText, SliceComponentProps } from "@prismicio/react";

import { Bounded } from "@/components/Bounded";

export type QuoteProps = SliceComponentProps<Content.QuoteSlice>;

const Quote = ({ slice }: QuoteProps): JSX.Element => {
	return (
		<Bounded as="section" size="wide">
			{isFilled.richText(slice.primary.quote) && (
				<div className="font-serif text-3xl italic leading-relaxed">
					&ldquo;
					<PrismicText field={slice.primary.quote} />
					&rdquo;
					{isFilled.keyText(slice.primary.source) && (
						<> &mdash; {slice.primary.source}</>
					)}
				</div>
			)}
		</Bounded>
	);
};

export default Quote;

// playground/slices/Quote/index.vue
<script setup lang="ts">
import { Content } from "@prismicio/client";

// The array passed to \`getSliceComponentProps\` is purely optional.
// Consider it as a visual hint for you when templating your slice.
defineProps(
	getSliceComponentProps<Content.QuoteSlice>([
		"slice",
		"index",
		"slices",
		"context",
	]),
);
</script>

<template>
	<Bounded as="section" size="wide">
		<div
			v-if="$prismic.asText(slice.primary.quote)"
			class="font-serif text-3xl italic leading-relaxed"
		>
			&ldquo;
			{{ $prismic.asText(slice.primary.quote) }}
			&rdquo;
			<template v-if="slice.primary.source">
				&mdash; {{ slice.primary.source }}
			</template>
		</div>
	</Bounded>
</template>
