// playground/slices/Text/index.vue
<script setup lang="ts">
import { Content } from "@prismicio/client";

// The array passed to \`getSliceComponentProps\` is purely optional.
// Consider it as a visual hint for you when templating your slice.
defineProps(
	getSliceComponentProps<Content.TextSlice>([
		"slice",
		"index",
		"slices",
		"context",
	]),
);
</script>

<template>
	<Bounded as="section">
		<PrismicRichText
			v-if="$prismic.asText(slice.primary.text)"
			class="font-serif leading-relaxed md:text-xl md:leading-relaxed"
			:field="slice.primary.text"
			wrapper="div"
		/>
	</Bounded>
</template>

// playground/src/slices/Text/index.tsx
import { Content, isFilled } from "@prismicio/client";
import { SliceComponentProps } from "@prismicio/react";

import { Bounded } from "@/components/Bounded";
import { PrismicRichText } from "@/components/PrismicRichText";

export type TextProps = SliceComponentProps<Content.TextSlice>;

const Text = ({ slice }: TextProps): JSX.Element => {
	return (
		<Bounded as="section">
			{isFilled.richText(slice.primary.text) && (
				<div className="font-serif leading-relaxed md:text-xl md:leading-relaxed">
					<PrismicRichText field={slice.primary.text} />
				</div>
			)}
		</Bounded>
	);
};

export default Text;
