// playground/components/Bounded.vue
<script setup lang="ts">
defineProps({
	as: {
		type: [String, Object, Function],
		default: "div",
	},
	size: {
		type: String,
		default: "base",
	},
});
</script>

<template>
	<Component :is="as" class="px-4 py-8 md:py-10 md:px-6 lg:py-12">
		<div
			class="mx-auto w-full"
			:class="{
				'max-w-xl': size === 'small',
				'max-w-3xl': size === 'base',
				'max-w-4xl': size === 'wide',
				'max-w-6xl': size === 'widest',
			}"
		>
			<slot />
		</div>
	</Component>
</template>

// playground/src/components/Bounded.tsx
import clsx from "clsx";

export function Bounded({
	as: Comp = "div",
	size = "base",
	className,
	children,
}: {
	as?: JSX.ElementType;
	size?: "small" | "base" | "wide" | "widest";
	className?: string;
	children?: JSX.Element | JSX.Element[] | false;
}): JSX.Element {
	return (
		<Comp className={clsx("px-4 py-8 md:px-6 md:py-10 lg:py-12", className)}>
			<div
				className={clsx(
					"mx-auto w-full",
					size === "small" && "max-w-xl",
					size === "base" && "max-w-3xl",
					size === "wide" && "max-w-4xl",
					size === "widest" && "max-w-6xl",
				)}
			>
				{children}
			</div>
		</Comp>
	);
}
