// packages/renderer-react/src/SliceCanvasRenderer.tsx
import * as React from "react";

import { RendererAPI, ClientRequestType } from "@prismicio/slice-canvas-com";
import {
	createStateManager,
	getDefaultManagedState,
	getDefaultProps,
	getDefaultSlices,
	SliceCanvasData,
	SliceCanvasProps,
} from "@prismicio/slice-canvas-renderer";

export type SliceCanvasRendererProps = {
	sliceZone: (slices: SliceCanvasData["slices"]) => React.ComponentType;
} & SliceCanvasProps;

export const SliceCanvasRenderer = (
	props: SliceCanvasRendererProps,
): JSX.Element => {
	const defaultProps = getDefaultProps();

	const stateManager = createStateManager();
	const [managedState, setManagedState] = React.useState(
		getDefaultManagedState(),
	);
	const [slices, setSlices] = React.useState(getDefaultSlices());

	React.useEffect(() => {
		stateManager.on("loaded", async (state) => {
			setManagedState(state);

			const api = new RendererAPI({
				[ClientRequestType.GetLibraries]: (req, res) => {
					return res.success(stateManager.getLibraries());
				},
				[ClientRequestType.SetSliceZone]: (req, res) => {
					setSlices(req.data);

					return res.success();
				},
				[ClientRequestType.SetSliceZoneFromSliceIDs]: (req, res) => {
					setSlices(stateManager.getSliceZoneFromSliceIDs(req.data));

					return res.success();
				},
			});

			await api.ready();
		});

		stateManager.load(props.state);
	}, []);

	return (
		<div
			className="slice-canvas-renderer"
			style={{
				zIndex: props.zIndex || defaultProps.zIndex,
				position: "fixed",
				top: 0,
				left: 0,
				width: "100%",
				height: "100vh",
				overflow: "auto",
				background: "#fefefe",
			}}
		>
			{managedState.data && slices.length ? props.sliceZone(slices) : null}
		</div>
	);
};

// packages/renderer-vue/src/SliceCanvasRenderer.vue
<template>
	<div class="slice-canvas-renderer" :style="{
		zIndex,
		position: 'fixed',
		top: 0,
		left: 0,
		width: '100%',
		height: '100vh',
		overflow: 'auto',
		background: '#fefefe'
	}">
		<slot :slices="slices" v-if="state" />
	</div>
</template>

<script lang="ts">
import Vue, { PropType } from "vue";
import { ExtendedVue } from "vue/types/vue";

import { RendererAPI, ClientRequestType } from "@prismicio/slice-canvas-com";
import {
	createStateManager,
	getDefaultState,
	SliceCanvasData,
	SliceCanvasProps,
	SliceCanvasOptions,
} from "@prismicio/slice-canvas-renderer";

export default {
	name: "SliceCanvasRenderer",
	props: {
		statePredicate: {
			type: Function as PropType<() => Promise<unknown>>,
			// @ts-expect-error - Only valid in real context
			default: () => import("~~/.slicemachine/slice-canvas-state.json"),
		},
		zIndex: {
			type: Number,
			default: 100,
		}
	},
	data(): SliceCanvasData {
		return {
			stateManager: createStateManager(),
			state: getDefaultState(),
			slices: [],
		};
	},
	mounted(this: SliceCanvasOptions) {
		this.stateManager.on("loaded", async (state) => {
			this.state = state;

			const api = new RendererAPI({
				[ClientRequestType.GetLibraries]: () => this.stateManager.getLibraries(),
				[ClientRequestType.SetSliceZone]: (message) => {
					this.slices = message.data;
				},
				[ClientRequestType.SetSliceZoneFromSliceIDs]: (message) => {
					this.slices = this.stateManager.setSliceZoneFromSliceIDs(message.data);
				}
			}, { debug: process.env.NODE_ENV === "development" });

			await api.ready();
		});

		this.stateManager.load(this.statePredicate);
	}
	// This is some weird ass trick to get around `Vue.extend` messing up `this` context, don't do this at home kids
} as unknown as ExtendedVue<Vue, SliceCanvasData, {}, {}, SliceCanvasProps>;
</script>
