// playground/src/slices/ContactForm/index.tsx
import { Content } from "@prismicio/client";
import { SliceComponentProps } from "@prismicio/react";

import { Bounded } from "@/components/Bounded";

const Field = ({
	label,
	children,
}: {
	label: string;
	children: JSX.Element | JSX.Element[];
}): JSX.Element => {
	return (
		<label>
			<span className="text-sm text-slate-500">{label}</span>
			{children}
		</label>
	);
};

const InputField = ({
	label,
	name,
	type = "text",
	placeholder,
	required = true,
}: {
	label: string;
	name: string;
	type?: string;
	placeholder: string;
	required?: boolean;
}): JSX.Element => {
	return (
		<Field label={label}>
			<input
				name={name}
				type={type}
				required={required}
				placeholder={placeholder}
				className="w-full rounded-none border-b border-slate-200 py-3 pl-3 pr-7 text-slate-800 placeholder-slate-400"
			/>
		</Field>
	);
};

const TextareaField = ({
	label,
	name,
	placeholder,
	required = true,
}: {
	label: string;
	name: string;
	placeholder: string;
	required?: boolean;
}): JSX.Element => {
	return (
		<Field label={label}>
			<textarea
				name={name}
				required={required}
				placeholder={placeholder}
				className="h-40 w-full rounded-none border-b border-slate-200 py-3 pl-3 pr-7 text-slate-800 placeholder-slate-400"
			/>
		</Field>
	);
};

export type ContactFormProps = SliceComponentProps<Content.ContactFormSlice>;

const ContactForm = (_props: ContactFormProps): JSX.Element => {
	return (
		<Bounded as="section" size="small">
			<form
				action="/api/contact"
				method="post"
				className="grid grid-cols-1 gap-6"
			>
				<InputField label="Name" name="name" placeholder="Jane Doe" />
				<InputField
					label="Email Address"
					name="email"
					type="email"
					placeholder="jane.doe@example.com"
				/>
				<TextareaField
					label="Message"
					name="message"
					placeholder="Write your message here…"
				/>
				<button
					type="submit"
					className="ml-auto inline-flex items-center gap-2"
				>
					Send message{" "}
					<span aria-hidden={true} className="text-xl">
						&rarr;
					</span>
				</button>
			</form>
		</Bounded>
	);
};

export default ContactForm;

// playground/slices/ContactForm/index.vue
<script setup lang="ts">
import { Content } from '@prismicio/client'

// The array passed to \`getSliceComponentProps\` is purely optional.
// Consider it as a visual hint for you when templating your slice.
defineProps(getSliceComponentProps<Content.ContactFormSlice>(
  ['slice', 'index', 'slices', 'context']
));
</script>

<template>
  <Bounded>
    <form
      action="/api/contact"
      method="post"
      class="grid grid-cols-1 gap-6"
    >
      <InputField
        label="Name"
        name="name"
        placeholder="Jane Doe"
      />
      <InputField
        label="Email Address"
        name="email"
        type="email"
        placeholder="jane.doe@example.com"
      />
      <TextareaField
        label="Message"
        name="message"
        placeholder="Write your message here…"
      />
      <button
        type="submit"
        class="ml-auto inline-flex items-center gap-2"
      >
        Send message <span
          aria-hidden="true"
          class="text-xl"
        >
          &rarr;
        </span>
      </button>
    </form>
  </Bounded>
</template>
